//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot_Alarm
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstrumentStatus", Namespace="http://schemas.datacontract.org/2004/07/Robot_Alarm")]
    public partial class InstrumentStatus : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string StatusField;
        
        private System.DateTime TimeCreatedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime TimeCreated
        {
            get
            {
                return this.TimeCreatedField;
            }
            set
            {
                this.TimeCreatedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlarmState", Namespace="http://schemas.datacontract.org/2004/07/Robot_Alarm")]
    public partial class AlarmState : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool AlarmOnField;
        
        private System.DateTime TimeTurnedOnField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool AlarmOn
        {
            get
            {
                return this.AlarmOnField;
            }
            set
            {
                this.AlarmOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime TimeTurnedOn
        {
            get
            {
                return this.TimeTurnedOnField;
            }
            set
            {
                this.TimeTurnedOnField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="IAlarm")]
public interface IAlarm
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlarm/GetInstrumentStatus", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlarm/GetInstrumentStatusResponse")]
    Robot_Alarm.InstrumentStatus GetInstrumentStatus();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlarm/GetAlarmStatus", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlarm/GetAlarmStatusResponse")]
    Robot_Alarm.AlarmState GetAlarmStatus();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlarm/TurnOnAlarm", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlarm/TurnOnAlarmResponse")]
    void TurnOnAlarm();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlarm/TurnOffAlarm", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlarm/TurnOffAlarmResponse")]
    void TurnOffAlarm();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlarm/UpdateStatus", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlarm/UpdateStatusResponse")]
    void UpdateStatus(string Status);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlarm/GetCameraImage1", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlarm/GetCameraImage1Response")]
    System.Drawing.Bitmap GetCameraImage1(out string UpdateTime);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlarm/GetCameraImage2", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlarm/GetCameraImage2Response")]
    System.Drawing.Bitmap GetCameraImage2(out string UpdateTime);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlarm/SetCameraImage1", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlarm/SetCameraImage1Response")]
    void SetCameraImage1(System.Drawing.Bitmap Image);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlarm/SetCameraImage2", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlarm/SetCameraImage2Response")]
    void SetCameraImage2(System.Drawing.Bitmap Image);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlarm/ReturnJPEGCamera1", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlarm/ReturnJPEGCamera1Response")]
    byte[] ReturnJPEGCamera1(out string updateTime);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlarm/ReturnJPEGCamera2", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlarm/ReturnJPEGCamera2Response")]
    byte[] ReturnJPEGCamera2(out string updateTime);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlarm/GetImageHeight", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlarm/GetImageHeightResponse")]
    int GetImageHeight();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IAlarm/GetImageWidth", ReplyAction="http://Microsoft.ServiceModel.Samples/IAlarm/GetImageWidthResponse")]
    int GetImageWidth();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IAlarmChannel : IAlarm, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class AlarmClient : System.ServiceModel.ClientBase<IAlarm>, IAlarm
{
    
    public AlarmClient()
    {
    }
    
    public AlarmClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AlarmClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AlarmClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AlarmClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Robot_Alarm.InstrumentStatus GetInstrumentStatus()
    {
        return base.Channel.GetInstrumentStatus();
    }
    
    public Robot_Alarm.AlarmState GetAlarmStatus()
    {
        return base.Channel.GetAlarmStatus();
    }
    
    public void TurnOnAlarm()
    {
        base.Channel.TurnOnAlarm();
    }
    
    public void TurnOffAlarm()
    {
        base.Channel.TurnOffAlarm();
    }
    
    public void UpdateStatus(string Status)
    {
        base.Channel.UpdateStatus(Status);
    }
    
    public System.Drawing.Bitmap GetCameraImage1(out string UpdateTime)
    {
        return base.Channel.GetCameraImage1(out UpdateTime);
    }
    
    public System.Drawing.Bitmap GetCameraImage2(out string UpdateTime)
    {
        return base.Channel.GetCameraImage2(out UpdateTime);
    }
    
    public void SetCameraImage1(System.Drawing.Bitmap Image)
    {
        base.Channel.SetCameraImage1(Image);
    }
    
    public void SetCameraImage2(System.Drawing.Bitmap Image)
    {
        base.Channel.SetCameraImage2(Image);
    }
    
    public byte[] ReturnJPEGCamera1(out string updateTime)
    {
        return base.Channel.ReturnJPEGCamera1(out updateTime);
    }
    
    public byte[] ReturnJPEGCamera2(out string updateTime)
    {
        return base.Channel.ReturnJPEGCamera2(out updateTime);
    }
    
    public int GetImageHeight()
    {
        return base.Channel.GetImageHeight();
    }
    
    public int GetImageWidth()
    {
        return base.Channel.GetImageWidth();
    }
}
